name: bizbloom
description: "A new Flutter project."
publish_to: 'none'
version: 5.0.0

environment:
  sdk: '>=3.0.0 <5.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl_utils: ^2.8.8
  fl_chart: ^1.0.0
  sqflite: ^2.3.2
  path: ^1.9.0


  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/env.json