name: bizbloom
description: "Calcula el punto de equilibrio de tu negocio"
publish_to: 'none'
version: 1.5.2

environment:
  sdk: '>=3.0.0 <5.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl_utils: ^2.8.8
  fl_chart: ^1.0.0
  sqflite: ^2.3.2
  path: ^1.9.0
  intl: any
  provider: ^6.0.5
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.2.1  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icono.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/graphic.png
    - assets/images/
    - assets/env.json
