// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQzXpMFC2Rlk6k_V35-xN5bVbxVPn5Lo4',
    appId: '1:455735825896:web:ca12a3bf5b00c3d54c405d',
    messagingSenderId: '455735825896',
    projectId: 'bizbloom-36757',
    authDomain: 'bizbloom-36757.firebaseapp.com',
    storageBucket: 'bizbloom-36757.firebasestorage.app',
    measurementId: 'G-9ZGMBGK3L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEWfem0VLX4YmQSdz8MNL7BEnS0dNfdho',
    appId: '1:455735825896:android:86bd6228ac9e64414c405d',
    messagingSenderId: '455735825896',
    projectId: 'bizbloom-36757',
    storageBucket: 'bizbloom-36757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgjTTjkocKO63lvfDoy42S-a7dpIRe-tQ',
    appId: '1:455735825896:ios:442c8884eb24f53b4c405d',
    messagingSenderId: '455735825896',
    projectId: 'bizbloom-36757',
    storageBucket: 'bizbloom-36757.firebasestorage.app',
    iosClientId: '455735825896-4hm50hjljm473at0c8cbt7h4tc1lqs94.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
